#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#number:
#  path: /number
#  controller: App\Controller\LuckyController::number

app_logout:
  path: /logout
  methods: GET